---@diagnostic disable: missing-return

---@enum df.death_type
df.death_type = {
    NONE = -1,
    OLD_AGE = 0,
    HUNGER = 1,
    THIRST = 2,
    SHOT = 3,
    BLEED = 4,
    DROWN = 5,
    SUFFOCATE = 6,
    STRUCK_DOWN = 7,
    SCUTTLE = 8, -- stuck wagons
    COLLISION = 9,
    MAGMA = 10, -- does not happen anymore?
    MAGMA_MIST = 11, -- does not happen anymore?
    DRAGONFIRE = 12,
    FIRE = 13,
    SCALD = 14, -- does not happen anymore?
    CAVEIN = 15,
    DRAWBRIDGE = 16,
    FALLING_ROCKS = 17, -- does not happen anymore?
    CHASM = 18,
    CAGE = 19,
    MURDER = 20,
    TRAP = 21,
    VANISH = 22, -- bogeyman
    QUIT = 23, -- Give in to starvation as adventurer
    ABANDON = 24,
    HEAT = 25,
    COLD = 26,
    SPIKE = 27,
    ENCASE_LAVA = 28,
    ENCASE_MAGMA = 29,
    ENCASE_ICE = 30,
    BEHEAD = 31, -- execution during worldgen
    CRUCIFY = 32, -- execution during worldgen
    BURY_ALIVE = 33, -- execution during worldgen
    DROWN_BY = 34, -- execution during worldgen
    BURN_ALIVE = 35, -- execution during worldgen
    FEED_TO_BEASTS = 36, -- execution during worldgen
    HACK_TO_PIECES = 37, -- execution during worldgen
    LEAVE_OUT_IN_AIR = 38, -- execution during worldgen
    BOIL = 39, -- material state change
    MELT = 40, -- material state change
    CONDENSE = 41, -- material state change
    SOLIDIFY = 42, -- material state change
    INFECTION = 43,
    MEMORIALIZE = 44, -- put to rest
    SCARE = 45,
    DARKNESS = 46, -- died in the dark
    COLLAPSE = 47, -- used in 0.31 for undead
    DRAIN_BLOOD = 48,
    SLAUGHTER = 49,
    VEHICLE = 50,
    FALLING_OBJECT = 51,
    LEAPT_FROM_HEIGHT = 52,
    DROWN_SELF = 53,
    EXECUTION_GENERIC = 54
}
