---@class df.building_stockpilest : df.building
---@field settings df.stockpile_settings
---@field storage df.stockpile_storage_infost  -- Stores container (barrels, bins) information
---@field links stockpile_links
---@field stockpile_flag building_stockpile_flag
---@field stockpile_number integer
---@field linked_stops hauling_stop[]
---@field find fun(id: integer): df.building_stockpilest
