---@class df.item_gloves_graphics_flag_material
---@field CLOTH integer
---@field LEATHER integer
---@field METAL integer
---@field BONE integer
---@field SHELL integer
---@field WOOD integer
---@field SILK integer
