---@class df.item_statue_graphics_flag
---@field material df.item_statue_graphics_flag_material[2]
---@field material_color_index integer[8]
---@field planned boolean
---@field is_item boolean
---@field artifact_index integer[8]
---@field quality integer[3]
