---@class df.item_food_container_graphics_type
---@field WOOD_BARREL integer
---@field METAL_BARREL integer
---@field WOOD_BARREL_ABSTRACT integer
---@field METAL_BARREL_ABSTRACT integer
---@field TOOL_WOOD integer
---@field TOOL_STONE integer
---@field TOOL_METAL integer
