---@class df.itemdef_default_improvementst
---@field type df.improvement_type
---@field specific_type df.itemimprovement_specific_type
---@field instrument_part string
---@field restriction df.tool_flags
