---@class df.gamest
---@field command_line df.command_linest
---@field main_interface df.main_interface
---@field minimap df.minimapst
---@field mod_manager df.mod_managerst
---@field hash_rng df.hash_rngst
---@field play_rng df.hash_rngst
---@field start_tick_count integer
---@field autosave_cycle integer
---@field want_to_quit_to_title boolean
---@field flash_11_by_3 integer[][][] @ 11x3x2 array
---@field flash_7_by_3 integer[][][] @ 7x3x2 array
---@field flash_4_by_3 integer[][][] @ 4x3x2 array
---@field external_flag df.external_flag
