---@class df.unit.status
---@field misc_traits unit_misc_trait[]
---@field eat_history unit_consumption_logst
---@field demand_timeout integer
---@field mandate_timeout integer
---@field attacker_ids integer[]
---@field attacker_cntdn integer[]
---@field face_direction integer
---@field artifact_name language_name
---@field souls unit_soul[]
---@field current_soul unit_soul
---@field demands unit_demand[]
---@field labors boolean[]
---@field wrestle_items unit_item_wrestle[]
---@field observed_traps integer[]
---@field complaints unit_complaint[]
---@field parleys unit_parley[]
---@field requests unit_request[]
---@field coin_debts unit_coin_debt[]
---@field commands command[]
---@field last_command_received_year integer
---@field last_command_received_season_count integer
---@field command_gait_index integer[]
---@field unit_command_flag unit_command_flags
---@field adv_sleep_timer integer
---@field recent_job_area coord
---@field recent_jobs coord_path

