---@class df.item_flags2
---@field has_rider boolean @ vehicle with a rider
---@field forbid_on_unretire boolean
---@field grown boolean
---@field location_reserved boolean @ possibly book/written-content-related
---@field utterly_destroyed boolean
---@field might_contain_artifact boolean