---@class df.burrow: df.base_class
---@field id integer
---@field name string
---@field tile integer
---@field fg_color integer
---@field bg_color integer
---@field block_x df.base_vector<integer, integer>
---@field block_y df.base_vector<integer, integer>
---@field block_z df.base_vector<integer, integer>
---@field units df.base_vector<integer, integer>
---@field flags df.burrow_flag
---@field solid_texpos integer
---@field blended_texpos integer
---@field symbol_index integer
---@field texture_r integer
---@field texture_g integer
---@field texture_b integer
---@field texture_br integer
---@field texture_bg integer
---@field texture_bb integer
---@field find fun(id: integer):df.burrow|nil

---@class df.burrow_flag
---@field limit_workshops boolean
---@field suspended boolean
